"""empty message

Revision ID: 172fdbdde7b
Revises: 4b5751f3f3fd
Create Date: 2014-12-12 15:38:14.737000

"""

# revision identifiers, used by Alembic.
revision = '172fdbdde7b'
down_revision = '4b5751f3f3fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
