"""empty message

Revision ID: 2524105ed12f
Revises: c7ab9eab4b8
Create Date: 2014-11-13 00:02:51.765000

"""

# revision identifiers, used by Alembic.
revision = '2524105ed12f'
down_revision = 'c7ab9eab4b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
