"""empty message

Revision ID: 3aaeeb035785
Revises: 40c175e229c2
Create Date: 2014-11-11 01:29:25.425000

"""

# revision identifiers, used by Alembic.
revision = '3aaeeb035785'
down_revision = '40c175e229c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
