"""empty message

Revision ID: 4b5751f3f3fd
Revises: 2524105ed12f
Create Date: 2014-12-10 22:06:10.224000

"""

# revision identifiers, used by Alembic.
revision = '4b5751f3f3fd'
down_revision = '2524105ed12f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    ### end Alembic commands ###
